dist: trusty

language: node_js

before_install:
  - node --version
  - npm --version
  - npm config set spin false

  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - npm install -g yarn
  - npm install -g grunt-cli
  - gem install compass
  - cd ui && yarn
  - cat npm-debug.log || true

script: grunt bundle && grunt uglify-and-rename && grunt web

cache:
  directories:
  - ui/node_modules

notifications:
  email: false
