# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Bahmni Apps - Stream3 Master

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.3]
        ruby: [2.5]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: sudo npm install -g bower 
    - run: sudo npm install -g grunt-cli 
    - run: sudo gem install compass  
    - run : sudo npm install --global yarn
    - run : sudo npm cache clean --force 
    - run : sudo bower cache clean --force 
    - run : rm -rf coverage/ 
    - run : cd ui && sudo yarn default --force
    - run : cd dist && zip -r ../target/bahmniapps.zip *
    - uses: actions/upload-artifact@v2
      with:
        name: BahmniApps
        path: ui/target/bahmniapps.zip

